### PR TITLE
Fix SiteSettings bugs

### LINKED ISSUE #4: Fix uninitialized SiteSettings
SiteSettings is not reachable from OmniAuth::Strategies::OAuth2

### LINKED ISSUE #5: Fix SiteSettings problems
SiteSettings take only default values, not values fulfilled in discourse administration panel.

### PR DESCRIPTION
**Pull request by fcheval**
Fix SiteSetting and plugin bugs.

Fix #5
Fix #4

### CODE REVIEW

File: plugin.rb [hunk 1]
```diff
@@ -1,11 +1,23 @@
+# name: ionisx
+# about: adds ionisx authenticaiton support to Discourse
```
Comment (tusbar) [inline plugin.rb]: adds => Add
authenticaiton => authentication

File: config/settings.yml [hunk 2]
```diff
@@ -1,4 +1,5 @@
-login:
+login: #set to ionisx to put the category out of /admin/Login
```
Comment (tusbar) [inline config/settings.yml:1]: Why this comment, why not just set the category to `ionisx`?

Comment (fcheval) [inline config/settings.yml:1]: It doesn't work actually. But I'm working on it.
